import { mkdir, readFile, writeFile } from "fs/promises";
import path from "path";
import { FrameworkInfo } from "./framework-detect";

export type InjectableFeature = {
  id: string;
  title: string;
  route: string;
  enabled: boolean;
};

const SLUSHIE_GUARD_MARKER = "// __slushie_guard__";

const NEXTJS_MIDDLEWARE_TEMPLATE = (features: InjectableFeature[]): string => {
  const disabledRoutes = features
    .filter((f) => !f.enabled)
    .map((f) => JSON.stringify(f.route));

  return `${SLUSHIE_GUARD_MARKER}
import { NextRequest, NextResponse } from "next/server";
import { readFile } from "fs/promises";
import path from "path";

const FEATURES_PATH = path.join(process.cwd(), "features.json");

async function getDisabledRoutes(): Promise<string[]> {
  try {
    const raw = await readFile(FEATURES_PATH, "utf-8");
    const { features } = JSON.parse(raw) as {
      features: { route: string; enabled: boolean }[];
    };
    return features
      .filter((f) => !f.enabled)
      .map((f) => f.route);
  } catch {
    // Fallback to build-time snapshot if file is unavailable
    return [${disabledRoutes.join(", ")}];
  }
}

export async function middleware(request: NextRequest) {
  const disabledRoutes = await getDisabledRoutes();
  const { pathname } = request.nextUrl;

  for (const route of disabledRoutes) {
    if (pathname === route || pathname.startsWith(route + "/")) {
      return NextResponse.redirect(new URL("/", request.url));
    }
  }

  return NextResponse.next();
}

export const config = {
  matcher: [
    "/((?!_next/static|_next/image|favicon\\.ico|api/).*)",
  ],
};
`;
};

const VITE_GUARD_MODULE = (features: InjectableFeature[]): string => {
  const featureMap = features.map(
    (f) => `  ${JSON.stringify(f.route)}: ${f.enabled}`
  );

  return `// __slushie_guard__
// Auto-generated by slushie — do not edit manually.

const featureRoutes: Record<string, boolean> = {
${featureMap.join(",\n")},
};

export function isFeatureEnabled(route: string): boolean {
  if (route in featureRoutes) {
    return featureRoutes[route];
  }
  // Routes not listed in the manifest are enabled by default.
  return true;
}
`;
};

export async function injectManifest(
  projectDir: string,
  features: InjectableFeature[],
  framework: FrameworkInfo
): Promise<void> {
  // 1. Write features.json to project root.
  const featuresJsonPath = path.join(projectDir, "features.json");
  await writeFile(
    featuresJsonPath,
    JSON.stringify({ features }, null, 2),
    "utf-8"
  );

  if (framework.name === "nextjs") {
    await injectNextjsMiddleware(projectDir, features);
  } else if (framework.name === "vite") {
    await injectViteGuard(projectDir, features);
  }
  // framework "unknown" — only features.json is written; no middleware injection.
}

async function injectNextjsMiddleware(
  projectDir: string,
  features: InjectableFeature[]
): Promise<void> {
  const middlewarePath = path.join(projectDir, "middleware.ts");

  // Check whether a middleware.ts already exists.
  let existing: string | null = null;
  try {
    existing = await readFile(middlewarePath, "utf-8");
  } catch {
    // File does not exist — nothing to back up.
  }

  if (existing !== null) {
    // Guard: do not double-inject.
    if (existing.includes(SLUSHIE_GUARD_MARKER)) {
      // Overwrite with refreshed feature list.
    } else {
      // Back up the original middleware before replacing it.
      await writeFile(
        path.join(projectDir, "middleware.ts.bak"),
        existing,
        "utf-8"
      );
    }
  }

  await writeFile(middlewarePath, NEXTJS_MIDDLEWARE_TEMPLATE(features), "utf-8");
}

async function injectViteGuard(
  projectDir: string,
  features: InjectableFeature[]
): Promise<void> {
  const guardDir = path.join(projectDir, "src");

  // Ensure src/ exists (handle projects that may not have it yet).
  await mkdir(guardDir, { recursive: true });

  const guardPath = path.join(guardDir, "_slushie-guard.ts");
  await writeFile(guardPath, VITE_GUARD_MODULE(features), "utf-8");
}
