import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { getCurrentUser } from "@/lib/auth";
import { ensureBranch, pushFiles, createPR } from "@/lib/github";

export async function POST(req: NextRequest, { params }: { params: Promise<{ id: string }> }) {
  const user = await getCurrentUser();
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  // Get user's GitHub token
  const dbUser = await prisma.user.findUnique({ where: { id: user.id }, select: { githubToken: true } });
  if (!dbUser?.githubToken) {
    return NextResponse.json({ error: "No GitHub token configured. Add one in your profile settings." }, { status: 400 });
  }
  const token = dbUser.githubToken;

  const { id } = await params;

  const feature = await prisma.feature.findUnique({
    where: { id },
    include: {
      project: true,
      builds: { where: { status: "complete" }, orderBy: { createdAt: "desc" }, take: 1 },
    },
  });

  if (!feature) return NextResponse.json({ error: "Feature not found" }, { status: 404 });
  if (!feature.project.githubRepo) {
    return NextResponse.json({ error: "No GitHub repo connected to this project" }, { status: 400 });
  }

  const latestBuild = feature.builds[0];
  if (!latestBuild) {
    return NextResponse.json({ error: "No completed build found for this feature" }, { status: 400 });
  }

  const githubRepo = feature.project.githubRepo;
  const baseBranch = feature.project.githubBranch || "dev";

  const slug = feature.title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
  const branchName = `feature/${slug}`;

  try {
    await ensureBranch(token, githubRepo, branchName, baseBranch);

    const generatedCode = latestBuild.generatedCode as any;
    const files: { path: string; content: string }[] = [];

    if (generatedCode?.files && Array.isArray(generatedCode.files)) {
      for (const file of generatedCode.files) {
        if (file.path && file.content) {
          files.push({ path: file.path, content: file.content });
        }
      }
    }

    if (files.length === 0) {
      return NextResponse.json({ error: "No files found in build output" }, { status: 400 });
    }

    const commitMessage = `feat: ${feature.title}\n\nGenerated by slushie build system`;
    await pushFiles(token, githubRepo, branchName, files, commitMessage);

    let prUrl = feature.githubPrUrl;
    let prNumber = feature.githubPrNumber;

    if (!prUrl) {
      const pr = await createPR(
        token,
        githubRepo,
        branchName,
        baseBranch,
        `feat: ${feature.title}`,
        `## ${feature.title}\n\n${feature.description}\n\n---\n*Generated by slushie build system*`
      );
      prUrl = pr.url;
      prNumber = pr.number;
    }

    await prisma.feature.update({
      where: { id },
      data: {
        githubBranch: branchName,
        githubPrUrl: prUrl,
        githubPrNumber: prNumber,
      },
    });

    return NextResponse.json({
      branch: branchName,
      filesCount: files.length,
      prUrl,
      prNumber,
    });
  } catch (err: any) {
    console.error("[github] Push failed:", err.message);
    return NextResponse.json({ error: err.message }, { status: 500 });
  }
}
